
package lv.bank.cards.soap.api.atm.soap.types;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-11-04T13:59:23.551+02:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "PaymentServerException", targetNamespace = "urn:PaymentServer")
public class PaymentServerFault extends Exception {

    private lv.bank.cards.soap.api.atm.soap.types.PaymentServerException faultInfo;

    public PaymentServerFault() {
        super();
    }

    public PaymentServerFault(String message) {
        super(message);
    }

    public PaymentServerFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PaymentServerFault(String message, lv.bank.cards.soap.api.atm.soap.types.PaymentServerException paymentServerException) {
        super(message);
        this.faultInfo = paymentServerException;
    }

    public PaymentServerFault(String message, lv.bank.cards.soap.api.atm.soap.types.PaymentServerException paymentServerException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = paymentServerException;
    }

    public lv.bank.cards.soap.api.atm.soap.types.PaymentServerException getFaultInfo() {
        return this.faultInfo;
    }
}
