//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.29 at 03:28:07 PM EEST 
//


package lv.bank.cards.auth;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;


/**
 * <p>Java class for iso element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="iso">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}fld000"/>
 *           &lt;element ref="{}fld001"/>
 *           &lt;element ref="{}fld002"/>
 *           &lt;element ref="{}fld003"/>
 *           &lt;element ref="{}fld004"/>
 *           &lt;element ref="{}fld005"/>
 *           &lt;element ref="{}fld006"/>
 *           &lt;element ref="{}fld007"/>
 *           &lt;element ref="{}fld008"/>
 *           &lt;element ref="{}fld009"/>
 *           &lt;element ref="{}fld010"/>
 *           &lt;element ref="{}fld011"/>
 *           &lt;element ref="{}fld012"/>
 *           &lt;element ref="{}fld013"/>
 *           &lt;element ref="{}fld014"/>
 *           &lt;element ref="{}fld015"/>
 *           &lt;element ref="{}fld016"/>
 *           &lt;element ref="{}fld017"/>
 *           &lt;element ref="{}fld018"/>
 *           &lt;element ref="{}fld019"/>
 *           &lt;element ref="{}fld020"/>
 *           &lt;element ref="{}fld021"/>
 *           &lt;element ref="{}fld022"/>
 *           &lt;element ref="{}fld023"/>
 *           &lt;element ref="{}fld024"/>
 *           &lt;element ref="{}fld025"/>
 *           &lt;element ref="{}fld026"/>
 *           &lt;element ref="{}fld027"/>
 *           &lt;element ref="{}fld028"/>
 *           &lt;element ref="{}fld029"/>
 *           &lt;element ref="{}fld030"/>
 *           &lt;element ref="{}fld031"/>
 *           &lt;element ref="{}fld032"/>
 *           &lt;element ref="{}fld033"/>
 *           &lt;element ref="{}fld034"/>
 *           &lt;element ref="{}fld035"/>
 *           &lt;element ref="{}fld036"/>
 *           &lt;element ref="{}fld037"/>
 *           &lt;element ref="{}fld038"/>
 *           &lt;element ref="{}fld039"/>
 *           &lt;element ref="{}fld040"/>
 *           &lt;element ref="{}fld041"/>
 *           &lt;element ref="{}fld042"/>
 *           &lt;element ref="{}fld043"/>
 *           &lt;element ref="{}fld044"/>
 *           &lt;element ref="{}fld045"/>
 *           &lt;element ref="{}fld046"/>
 *           &lt;element ref="{}fld047"/>
 *           &lt;element ref="{}fld048"/>
 *           &lt;element ref="{}fld049"/>
 *           &lt;element ref="{}fld050"/>
 *           &lt;element ref="{}fld051"/>
 *           &lt;element ref="{}fld052"/>
 *           &lt;element ref="{}fld053"/>
 *           &lt;element ref="{}fld054"/>
 *           &lt;element ref="{}fld055"/>
 *           &lt;element ref="{}fld056"/>
 *           &lt;element ref="{}fld057"/>
 *           &lt;element ref="{}fld058"/>
 *           &lt;element ref="{}fld059"/>
 *           &lt;element ref="{}fld060"/>
 *           &lt;element ref="{}fld061"/>
 *           &lt;element ref="{}fld062"/>
 *           &lt;element ref="{}fld063"/>
 *           &lt;element ref="{}fld064"/>
 *           &lt;element ref="{}fld065"/>
 *           &lt;element ref="{}fld066"/>
 *           &lt;element ref="{}fld067"/>
 *           &lt;element ref="{}fld068"/>
 *           &lt;element ref="{}fld069"/>
 *           &lt;element ref="{}fld070"/>
 *           &lt;element ref="{}fld071"/>
 *           &lt;element ref="{}fld072"/>
 *           &lt;element ref="{}fld073"/>
 *           &lt;element ref="{}fld074"/>
 *           &lt;element ref="{}fld075"/>
 *           &lt;element ref="{}fld076"/>
 *           &lt;element ref="{}fld077"/>
 *           &lt;element ref="{}fld078"/>
 *           &lt;element ref="{}fld079"/>
 *           &lt;element ref="{}fld080"/>
 *           &lt;element ref="{}fld081"/>
 *           &lt;element ref="{}fld082"/>
 *           &lt;element ref="{}fld083"/>
 *           &lt;element ref="{}fld084"/>
 *           &lt;element ref="{}fld085"/>
 *           &lt;element ref="{}fld086"/>
 *           &lt;element ref="{}fld087"/>
 *           &lt;element ref="{}fld088"/>
 *           &lt;element ref="{}fld089"/>
 *           &lt;element ref="{}fld090"/>
 *           &lt;element ref="{}fld091"/>
 *           &lt;element ref="{}fld092"/>
 *           &lt;element ref="{}fld093"/>
 *           &lt;element ref="{}fld094"/>
 *           &lt;element ref="{}fld095"/>
 *           &lt;element ref="{}fld096"/>
 *           &lt;element ref="{}fld097"/>
 *           &lt;element ref="{}fld098"/>
 *           &lt;element ref="{}fld099"/>
 *           &lt;element ref="{}fld100"/>
 *           &lt;element ref="{}fld101"/>
 *           &lt;element ref="{}fld102"/>
 *           &lt;element ref="{}fld103"/>
 *           &lt;element ref="{}fld104"/>
 *           &lt;element ref="{}fld105"/>
 *           &lt;element ref="{}fld106"/>
 *           &lt;element ref="{}fld107"/>
 *           &lt;element ref="{}fld108"/>
 *           &lt;element ref="{}fld109"/>
 *           &lt;element ref="{}fld110"/>
 *           &lt;element ref="{}fld111"/>
 *           &lt;element ref="{}fld112"/>
 *           &lt;element ref="{}fld113"/>
 *           &lt;element ref="{}fld114"/>
 *           &lt;element ref="{}fld115"/>
 *           &lt;element ref="{}fld116"/>
 *           &lt;element ref="{}fld117"/>
 *           &lt;element ref="{}fld118"/>
 *           &lt;element ref="{}fld119"/>
 *           &lt;element ref="{}fld120"/>
 *           &lt;element ref="{}fld121"/>
 *           &lt;element ref="{}fld122"/>
 *           &lt;element ref="{}fld123"/>
 *           &lt;element ref="{}fld124"/>
 *           &lt;element ref="{}fld125"/>
 *           &lt;element ref="{}fld126"/>
 *           &lt;element ref="{}fld127"/>
 *           &lt;element ref="{}fld128"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "fld000",
        "fld001",
        "fld002",
        "fld003",
        "fld004",
        "fld005",
        "fld006",
        "fld007",
        "fld008",
        "fld009",
        "fld010",
        "fld011",
        "fld012",
        "fld013",
        "fld014",
        "fld015",
        "fld016",
        "fld017",
        "fld018",
        "fld019",
        "fld020",
        "fld021",
        "fld022",
        "fld023",
        "fld024",
        "fld025",
        "fld026",
        "fld027",
        "fld028",
        "fld029",
        "fld030",
        "fld031",
        "fld032",
        "fld033",
        "fld034",
        "fld035",
        "fld036",
        "fld037",
        "fld038",
        "fld039",
        "fld040",
        "fld041",
        "fld042",
        "fld043",
        "fld044",
        "fld045",
        "fld046",
        "fld047",
        "fld048",
        "fld049",
        "fld050",
        "fld051",
        "fld052",
        "fld053",
        "fld054",
        "fld055",
        "fld056",
        "fld057",
        "fld058",
        "fld059",
        "fld060",
        "fld061",
        "fld062",
        "fld063",
        "fld064",
        "fld065",
        "fld066",
        "fld067",
        "fld068",
        "fld069",
        "fld070",
        "fld071",
        "fld072",
        "fld073",
        "fld074",
        "fld075",
        "fld076",
        "fld077",
        "fld078",
        "fld079",
        "fld080",
        "fld081",
        "fld082",
        "fld083",
        "fld084",
        "fld085",
        "fld086",
        "fld087",
        "fld088",
        "fld089",
        "fld090",
        "fld091",
        "fld092",
        "fld093",
        "fld094",
        "fld095",
        "fld096",
        "fld097",
        "fld098",
        "fld099",
        "fld100",
        "fld101",
        "fld102",
        "fld103",
        "fld104",
        "fld105",
        "fld106",
        "fld107",
        "fld108",
        "fld109",
        "fld110",
        "fld111",
        "fld112",
        "fld113",
        "fld114",
        "fld115",
        "fld116",
        "fld117",
        "fld118",
        "fld119",
        "fld120",
        "fld121",
        "fld122",
        "fld123",
        "fld124",
        "fld125",
        "fld126",
        "fld127",
        "fld128"
})
@XmlRootElement(name = "iso")
public class Iso {

    protected String fld000;
    protected String fld001;
    protected String fld002;
    protected String fld003;
    protected String fld004;
    protected String fld005;
    protected String fld006;
    protected String fld007;
    protected String fld008;
    protected String fld009;
    protected String fld010;
    protected String fld011;
    protected String fld012;
    protected String fld013;
    protected String fld014;
    protected String fld015;
    protected String fld016;
    protected String fld017;
    protected String fld018;
    protected String fld019;
    protected String fld020;
    protected String fld021;
    protected String fld022;
    protected String fld023;
    protected String fld024;
    protected String fld025;
    protected String fld026;
    protected String fld027;
    protected String fld028;
    protected String fld029;
    protected String fld030;
    protected String fld031;
    protected String fld032;
    protected String fld033;
    protected String fld034;
    protected String fld035;
    protected String fld036;
    protected String fld037;
    protected String fld038;
    protected String fld039;
    protected String fld040;
    protected String fld041;
    protected String fld042;
    protected String fld043;
    protected String fld044;
    protected String fld045;
    protected String fld046;
    protected String fld047;
    protected String fld048;
    protected String fld049;
    protected String fld050;
    protected String fld051;
    protected String fld052;
    protected String fld053;
    protected String fld054;
    protected String fld055;
    protected String fld056;
    protected String fld057;
    protected String fld058;
    protected String fld059;
    protected String fld060;
    protected String fld061;
    protected String fld062;
    protected String fld063;
    protected String fld064;
    protected String fld065;
    protected String fld066;
    protected String fld067;
    protected String fld068;
    protected String fld069;
    protected String fld070;
    protected String fld071;
    protected String fld072;
    protected String fld073;
    protected String fld074;
    protected String fld075;
    protected String fld076;
    protected String fld077;
    protected String fld078;
    protected String fld079;
    protected String fld080;
    protected String fld081;
    protected String fld082;
    protected String fld083;
    protected String fld084;
    protected String fld085;
    protected String fld086;
    protected String fld087;
    protected String fld088;
    protected String fld089;
    protected String fld090;
    protected String fld091;
    protected String fld092;
    protected String fld093;
    protected String fld094;
    protected String fld095;
    protected String fld096;
    protected String fld097;
    protected String fld098;
    protected String fld099;
    protected String fld100;
    protected String fld101;
    protected String fld102;
    protected String fld103;
    protected String fld104;
    protected String fld105;
    protected String fld106;
    protected String fld107;
    protected String fld108;
    protected String fld109;
    protected String fld110;
    protected String fld111;
    protected String fld112;
    protected String fld113;
    protected String fld114;
    protected String fld115;
    protected String fld116;
    protected String fld117;
    protected String fld118;
    protected String fld119;
    protected String fld120;
    protected String fld121;
    protected String fld122;
    protected String fld123;
    protected String fld124;
    protected String fld125;
    protected String fld126;
    protected String fld127;
    protected String fld128;

    /**
     * Gets the value of the fld000 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld000() {
        return fld000;
    }

    /**
     * Sets the value of the fld000 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld000(String value) {
        this.fld000 = value;
    }

    /**
     * Gets the value of the fld001 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld001() {
        return fld001;
    }

    /**
     * Sets the value of the fld001 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld001(String value) {
        this.fld001 = value;
    }

    /**
     * Gets the value of the fld002 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld002() {
        return fld002;
    }

    /**
     * Sets the value of the fld002 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld002(String value) {
        this.fld002 = value;
    }

    /**
     * Gets the value of the fld003 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld003() {
        return fld003;
    }

    /**
     * Sets the value of the fld003 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld003(String value) {
        this.fld003 = value;
    }

    /**
     * Gets the value of the fld004 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld004() {
        return fld004;
    }

    /**
     * Sets the value of the fld004 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld004(String value) {
        this.fld004 = value;
    }

    /**
     * Gets the value of the fld005 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld005() {
        return fld005;
    }

    /**
     * Sets the value of the fld005 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld005(String value) {
        this.fld005 = value;
    }

    /**
     * Gets the value of the fld006 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld006() {
        return fld006;
    }

    /**
     * Sets the value of the fld006 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld006(String value) {
        this.fld006 = value;
    }

    /**
     * Gets the value of the fld007 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld007() {
        return fld007;
    }

    /**
     * Sets the value of the fld007 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld007(String value) {
        this.fld007 = value;
    }

    /**
     * Gets the value of the fld008 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld008() {
        return fld008;
    }

    /**
     * Sets the value of the fld008 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld008(String value) {
        this.fld008 = value;
    }

    /**
     * Gets the value of the fld009 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld009() {
        return fld009;
    }

    /**
     * Sets the value of the fld009 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld009(String value) {
        this.fld009 = value;
    }

    /**
     * Gets the value of the fld010 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld010() {
        return fld010;
    }

    /**
     * Sets the value of the fld010 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld010(String value) {
        this.fld010 = value;
    }

    /**
     * Gets the value of the fld011 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld011() {
        return fld011;
    }

    /**
     * Sets the value of the fld011 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld011(String value) {
        this.fld011 = value;
    }

    /**
     * Gets the value of the fld012 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld012() {
        return fld012;
    }

    /**
     * Sets the value of the fld012 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld012(String value) {
        this.fld012 = value;
    }

    /**
     * Gets the value of the fld013 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld013() {
        return fld013;
    }

    /**
     * Sets the value of the fld013 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld013(String value) {
        this.fld013 = value;
    }

    /**
     * Gets the value of the fld014 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld014() {
        return fld014;
    }

    /**
     * Sets the value of the fld014 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld014(String value) {
        this.fld014 = value;
    }

    /**
     * Gets the value of the fld015 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld015() {
        return fld015;
    }

    /**
     * Sets the value of the fld015 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld015(String value) {
        this.fld015 = value;
    }

    /**
     * Gets the value of the fld016 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld016() {
        return fld016;
    }

    /**
     * Sets the value of the fld016 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld016(String value) {
        this.fld016 = value;
    }

    /**
     * Gets the value of the fld017 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld017() {
        return fld017;
    }

    /**
     * Sets the value of the fld017 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld017(String value) {
        this.fld017 = value;
    }

    /**
     * Gets the value of the fld018 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld018() {
        return fld018;
    }

    /**
     * Sets the value of the fld018 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld018(String value) {
        this.fld018 = value;
    }

    /**
     * Gets the value of the fld019 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld019() {
        return fld019;
    }

    /**
     * Sets the value of the fld019 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld019(String value) {
        this.fld019 = value;
    }

    /**
     * Gets the value of the fld020 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld020() {
        return fld020;
    }

    /**
     * Sets the value of the fld020 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld020(String value) {
        this.fld020 = value;
    }

    /**
     * Gets the value of the fld021 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld021() {
        return fld021;
    }

    /**
     * Sets the value of the fld021 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld021(String value) {
        this.fld021 = value;
    }

    /**
     * Gets the value of the fld022 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld022() {
        return fld022;
    }

    /**
     * Sets the value of the fld022 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld022(String value) {
        this.fld022 = value;
    }

    /**
     * Gets the value of the fld023 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld023() {
        return fld023;
    }

    /**
     * Sets the value of the fld023 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld023(String value) {
        this.fld023 = value;
    }

    /**
     * Gets the value of the fld024 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld024() {
        return fld024;
    }

    /**
     * Sets the value of the fld024 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld024(String value) {
        this.fld024 = value;
    }

    /**
     * Gets the value of the fld025 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld025() {
        return fld025;
    }

    /**
     * Sets the value of the fld025 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld025(String value) {
        this.fld025 = value;
    }

    /**
     * Gets the value of the fld026 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld026() {
        return fld026;
    }

    /**
     * Sets the value of the fld026 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld026(String value) {
        this.fld026 = value;
    }

    /**
     * Gets the value of the fld027 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld027() {
        return fld027;
    }

    /**
     * Sets the value of the fld027 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld027(String value) {
        this.fld027 = value;
    }

    /**
     * Gets the value of the fld028 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld028() {
        return fld028;
    }

    /**
     * Sets the value of the fld028 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld028(String value) {
        this.fld028 = value;
    }

    /**
     * Gets the value of the fld029 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld029() {
        return fld029;
    }

    /**
     * Sets the value of the fld029 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld029(String value) {
        this.fld029 = value;
    }

    /**
     * Gets the value of the fld030 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld030() {
        return fld030;
    }

    /**
     * Sets the value of the fld030 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld030(String value) {
        this.fld030 = value;
    }

    /**
     * Gets the value of the fld031 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld031() {
        return fld031;
    }

    /**
     * Sets the value of the fld031 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld031(String value) {
        this.fld031 = value;
    }

    /**
     * Gets the value of the fld032 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld032() {
        return fld032;
    }

    /**
     * Sets the value of the fld032 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld032(String value) {
        this.fld032 = value;
    }

    /**
     * Gets the value of the fld033 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld033() {
        return fld033;
    }

    /**
     * Sets the value of the fld033 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld033(String value) {
        this.fld033 = value;
    }

    /**
     * Gets the value of the fld034 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld034() {
        return fld034;
    }

    /**
     * Sets the value of the fld034 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld034(String value) {
        this.fld034 = value;
    }

    /**
     * Gets the value of the fld035 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld035() {
        return fld035;
    }

    /**
     * Sets the value of the fld035 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld035(String value) {
        this.fld035 = value;
    }

    /**
     * Gets the value of the fld036 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld036() {
        return fld036;
    }

    /**
     * Sets the value of the fld036 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld036(String value) {
        this.fld036 = value;
    }

    /**
     * Gets the value of the fld037 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld037() {
        return fld037;
    }

    /**
     * Sets the value of the fld037 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld037(String value) {
        this.fld037 = value;
    }

    /**
     * Gets the value of the fld038 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld038() {
        return fld038;
    }

    /**
     * Sets the value of the fld038 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld038(String value) {
        this.fld038 = value;
    }

    /**
     * Gets the value of the fld039 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld039() {
        return fld039;
    }

    /**
     * Sets the value of the fld039 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld039(String value) {
        this.fld039 = value;
    }

    /**
     * Gets the value of the fld040 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld040() {
        return fld040;
    }

    /**
     * Sets the value of the fld040 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld040(String value) {
        this.fld040 = value;
    }

    /**
     * Gets the value of the fld041 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld041() {
        return fld041;
    }

    /**
     * Sets the value of the fld041 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld041(String value) {
        this.fld041 = value;
    }

    /**
     * Gets the value of the fld042 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld042() {
        return fld042;
    }

    /**
     * Sets the value of the fld042 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld042(String value) {
        this.fld042 = value;
    }

    /**
     * Gets the value of the fld043 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld043() {
        return fld043;
    }

    /**
     * Sets the value of the fld043 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld043(String value) {
        this.fld043 = value;
    }

    /**
     * Gets the value of the fld044 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld044() {
        return fld044;
    }

    /**
     * Sets the value of the fld044 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld044(String value) {
        this.fld044 = value;
    }

    /**
     * Gets the value of the fld045 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld045() {
        return fld045;
    }

    /**
     * Sets the value of the fld045 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld045(String value) {
        this.fld045 = value;
    }

    /**
     * Gets the value of the fld046 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld046() {
        return fld046;
    }

    /**
     * Sets the value of the fld046 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld046(String value) {
        this.fld046 = value;
    }

    /**
     * Gets the value of the fld047 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld047() {
        return fld047;
    }

    /**
     * Sets the value of the fld047 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld047(String value) {
        this.fld047 = value;
    }

    /**
     * Gets the value of the fld048 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld048() {
        return fld048;
    }

    /**
     * Sets the value of the fld048 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld048(String value) {
        this.fld048 = value;
    }

    /**
     * Gets the value of the fld049 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld049() {
        return fld049;
    }

    /**
     * Sets the value of the fld049 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld049(String value) {
        this.fld049 = value;
    }

    /**
     * Gets the value of the fld050 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld050() {
        return fld050;
    }

    /**
     * Sets the value of the fld050 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld050(String value) {
        this.fld050 = value;
    }

    /**
     * Gets the value of the fld051 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld051() {
        return fld051;
    }

    /**
     * Sets the value of the fld051 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld051(String value) {
        this.fld051 = value;
    }

    /**
     * Gets the value of the fld052 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld052() {
        return fld052;
    }

    /**
     * Sets the value of the fld052 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld052(String value) {
        this.fld052 = value;
    }

    /**
     * Gets the value of the fld053 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld053() {
        return fld053;
    }

    /**
     * Sets the value of the fld053 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld053(String value) {
        this.fld053 = value;
    }

    /**
     * Gets the value of the fld054 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld054() {
        return fld054;
    }

    /**
     * Sets the value of the fld054 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld054(String value) {
        this.fld054 = value;
    }

    /**
     * Gets the value of the fld055 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld055() {
        return fld055;
    }

    /**
     * Sets the value of the fld055 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld055(String value) {
        this.fld055 = value;
    }

    /**
     * Gets the value of the fld056 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld056() {
        return fld056;
    }

    /**
     * Sets the value of the fld056 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld056(String value) {
        this.fld056 = value;
    }

    /**
     * Gets the value of the fld057 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld057() {
        return fld057;
    }

    /**
     * Sets the value of the fld057 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld057(String value) {
        this.fld057 = value;
    }

    /**
     * Gets the value of the fld058 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld058() {
        return fld058;
    }

    /**
     * Sets the value of the fld058 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld058(String value) {
        this.fld058 = value;
    }

    /**
     * Gets the value of the fld059 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld059() {
        return fld059;
    }

    /**
     * Sets the value of the fld059 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld059(String value) {
        this.fld059 = value;
    }

    /**
     * Gets the value of the fld060 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld060() {
        return fld060;
    }

    /**
     * Sets the value of the fld060 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld060(String value) {
        this.fld060 = value;
    }

    /**
     * Gets the value of the fld061 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld061() {
        return fld061;
    }

    /**
     * Sets the value of the fld061 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld061(String value) {
        this.fld061 = value;
    }

    /**
     * Gets the value of the fld062 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld062() {
        return fld062;
    }

    /**
     * Sets the value of the fld062 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld062(String value) {
        this.fld062 = value;
    }

    /**
     * Gets the value of the fld063 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld063() {
        return fld063;
    }

    /**
     * Sets the value of the fld063 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld063(String value) {
        this.fld063 = value;
    }

    /**
     * Gets the value of the fld064 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld064() {
        return fld064;
    }

    /**
     * Sets the value of the fld064 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld064(String value) {
        this.fld064 = value;
    }

    /**
     * Gets the value of the fld065 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld065() {
        return fld065;
    }

    /**
     * Sets the value of the fld065 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld065(String value) {
        this.fld065 = value;
    }

    /**
     * Gets the value of the fld066 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld066() {
        return fld066;
    }

    /**
     * Sets the value of the fld066 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld066(String value) {
        this.fld066 = value;
    }

    /**
     * Gets the value of the fld067 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld067() {
        return fld067;
    }

    /**
     * Sets the value of the fld067 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld067(String value) {
        this.fld067 = value;
    }

    /**
     * Gets the value of the fld068 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld068() {
        return fld068;
    }

    /**
     * Sets the value of the fld068 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld068(String value) {
        this.fld068 = value;
    }

    /**
     * Gets the value of the fld069 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld069() {
        return fld069;
    }

    /**
     * Sets the value of the fld069 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld069(String value) {
        this.fld069 = value;
    }

    /**
     * Gets the value of the fld070 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld070() {
        return fld070;
    }

    /**
     * Sets the value of the fld070 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld070(String value) {
        this.fld070 = value;
    }

    /**
     * Gets the value of the fld071 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld071() {
        return fld071;
    }

    /**
     * Sets the value of the fld071 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld071(String value) {
        this.fld071 = value;
    }

    /**
     * Gets the value of the fld072 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld072() {
        return fld072;
    }

    /**
     * Sets the value of the fld072 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld072(String value) {
        this.fld072 = value;
    }

    /**
     * Gets the value of the fld073 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld073() {
        return fld073;
    }

    /**
     * Sets the value of the fld073 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld073(String value) {
        this.fld073 = value;
    }

    /**
     * Gets the value of the fld074 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld074() {
        return fld074;
    }

    /**
     * Sets the value of the fld074 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld074(String value) {
        this.fld074 = value;
    }

    /**
     * Gets the value of the fld075 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld075() {
        return fld075;
    }

    /**
     * Sets the value of the fld075 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld075(String value) {
        this.fld075 = value;
    }

    /**
     * Gets the value of the fld076 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld076() {
        return fld076;
    }

    /**
     * Sets the value of the fld076 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld076(String value) {
        this.fld076 = value;
    }

    /**
     * Gets the value of the fld077 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld077() {
        return fld077;
    }

    /**
     * Sets the value of the fld077 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld077(String value) {
        this.fld077 = value;
    }

    /**
     * Gets the value of the fld078 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld078() {
        return fld078;
    }

    /**
     * Sets the value of the fld078 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld078(String value) {
        this.fld078 = value;
    }

    /**
     * Gets the value of the fld079 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld079() {
        return fld079;
    }

    /**
     * Sets the value of the fld079 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld079(String value) {
        this.fld079 = value;
    }

    /**
     * Gets the value of the fld080 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld080() {
        return fld080;
    }

    /**
     * Sets the value of the fld080 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld080(String value) {
        this.fld080 = value;
    }

    /**
     * Gets the value of the fld081 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld081() {
        return fld081;
    }

    /**
     * Sets the value of the fld081 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld081(String value) {
        this.fld081 = value;
    }

    /**
     * Gets the value of the fld082 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld082() {
        return fld082;
    }

    /**
     * Sets the value of the fld082 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld082(String value) {
        this.fld082 = value;
    }

    /**
     * Gets the value of the fld083 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld083() {
        return fld083;
    }

    /**
     * Sets the value of the fld083 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld083(String value) {
        this.fld083 = value;
    }

    /**
     * Gets the value of the fld084 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld084() {
        return fld084;
    }

    /**
     * Sets the value of the fld084 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld084(String value) {
        this.fld084 = value;
    }

    /**
     * Gets the value of the fld085 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld085() {
        return fld085;
    }

    /**
     * Sets the value of the fld085 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld085(String value) {
        this.fld085 = value;
    }

    /**
     * Gets the value of the fld086 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld086() {
        return fld086;
    }

    /**
     * Sets the value of the fld086 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld086(String value) {
        this.fld086 = value;
    }

    /**
     * Gets the value of the fld087 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld087() {
        return fld087;
    }

    /**
     * Sets the value of the fld087 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld087(String value) {
        this.fld087 = value;
    }

    /**
     * Gets the value of the fld088 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld088() {
        return fld088;
    }

    /**
     * Sets the value of the fld088 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld088(String value) {
        this.fld088 = value;
    }

    /**
     * Gets the value of the fld089 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld089() {
        return fld089;
    }

    /**
     * Sets the value of the fld089 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld089(String value) {
        this.fld089 = value;
    }

    /**
     * Gets the value of the fld090 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld090() {
        return fld090;
    }

    /**
     * Sets the value of the fld090 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld090(String value) {
        this.fld090 = value;
    }

    /**
     * Gets the value of the fld091 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld091() {
        return fld091;
    }

    /**
     * Sets the value of the fld091 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld091(String value) {
        this.fld091 = value;
    }

    /**
     * Gets the value of the fld092 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld092() {
        return fld092;
    }

    /**
     * Sets the value of the fld092 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld092(String value) {
        this.fld092 = value;
    }

    /**
     * Gets the value of the fld093 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld093() {
        return fld093;
    }

    /**
     * Sets the value of the fld093 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld093(String value) {
        this.fld093 = value;
    }

    /**
     * Gets the value of the fld094 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld094() {
        return fld094;
    }

    /**
     * Sets the value of the fld094 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld094(String value) {
        this.fld094 = value;
    }

    /**
     * Gets the value of the fld095 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld095() {
        return fld095;
    }

    /**
     * Sets the value of the fld095 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld095(String value) {
        this.fld095 = value;
    }

    /**
     * Gets the value of the fld096 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld096() {
        return fld096;
    }

    /**
     * Sets the value of the fld096 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld096(String value) {
        this.fld096 = value;
    }

    /**
     * Gets the value of the fld097 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld097() {
        return fld097;
    }

    /**
     * Sets the value of the fld097 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld097(String value) {
        this.fld097 = value;
    }

    /**
     * Gets the value of the fld098 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld098() {
        return fld098;
    }

    /**
     * Sets the value of the fld098 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld098(String value) {
        this.fld098 = value;
    }

    /**
     * Gets the value of the fld099 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld099() {
        return fld099;
    }

    /**
     * Sets the value of the fld099 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld099(String value) {
        this.fld099 = value;
    }

    /**
     * Gets the value of the fld100 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld100() {
        return fld100;
    }

    /**
     * Sets the value of the fld100 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld100(String value) {
        this.fld100 = value;
    }

    /**
     * Gets the value of the fld101 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld101() {
        return fld101;
    }

    /**
     * Sets the value of the fld101 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld101(String value) {
        this.fld101 = value;
    }

    /**
     * Gets the value of the fld102 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld102() {
        return fld102;
    }

    /**
     * Sets the value of the fld102 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld102(String value) {
        this.fld102 = value;
    }

    /**
     * Gets the value of the fld103 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld103() {
        return fld103;
    }

    /**
     * Sets the value of the fld103 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld103(String value) {
        this.fld103 = value;
    }

    /**
     * Gets the value of the fld104 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld104() {
        return fld104;
    }

    /**
     * Sets the value of the fld104 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld104(String value) {
        this.fld104 = value;
    }

    /**
     * Gets the value of the fld105 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld105() {
        return fld105;
    }

    /**
     * Sets the value of the fld105 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld105(String value) {
        this.fld105 = value;
    }

    /**
     * Gets the value of the fld106 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld106() {
        return fld106;
    }

    /**
     * Sets the value of the fld106 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld106(String value) {
        this.fld106 = value;
    }

    /**
     * Gets the value of the fld107 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld107() {
        return fld107;
    }

    /**
     * Sets the value of the fld107 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld107(String value) {
        this.fld107 = value;
    }

    /**
     * Gets the value of the fld108 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld108() {
        return fld108;
    }

    /**
     * Sets the value of the fld108 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld108(String value) {
        this.fld108 = value;
    }

    /**
     * Gets the value of the fld109 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld109() {
        return fld109;
    }

    /**
     * Sets the value of the fld109 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld109(String value) {
        this.fld109 = value;
    }

    /**
     * Gets the value of the fld110 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld110() {
        return fld110;
    }

    /**
     * Sets the value of the fld110 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld110(String value) {
        this.fld110 = value;
    }

    /**
     * Gets the value of the fld111 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld111() {
        return fld111;
    }

    /**
     * Sets the value of the fld111 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld111(String value) {
        this.fld111 = value;
    }

    /**
     * Gets the value of the fld112 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld112() {
        return fld112;
    }

    /**
     * Sets the value of the fld112 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld112(String value) {
        this.fld112 = value;
    }

    /**
     * Gets the value of the fld113 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld113() {
        return fld113;
    }

    /**
     * Sets the value of the fld113 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld113(String value) {
        this.fld113 = value;
    }

    /**
     * Gets the value of the fld114 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld114() {
        return fld114;
    }

    /**
     * Sets the value of the fld114 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld114(String value) {
        this.fld114 = value;
    }

    /**
     * Gets the value of the fld115 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld115() {
        return fld115;
    }

    /**
     * Sets the value of the fld115 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld115(String value) {
        this.fld115 = value;
    }

    /**
     * Gets the value of the fld116 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld116() {
        return fld116;
    }

    /**
     * Sets the value of the fld116 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld116(String value) {
        this.fld116 = value;
    }

    /**
     * Gets the value of the fld117 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld117() {
        return fld117;
    }

    /**
     * Sets the value of the fld117 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld117(String value) {
        this.fld117 = value;
    }

    /**
     * Gets the value of the fld118 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld118() {
        return fld118;
    }

    /**
     * Sets the value of the fld118 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld118(String value) {
        this.fld118 = value;
    }

    /**
     * Gets the value of the fld119 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld119() {
        return fld119;
    }

    /**
     * Sets the value of the fld119 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld119(String value) {
        this.fld119 = value;
    }

    /**
     * Gets the value of the fld120 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld120() {
        return fld120;
    }

    /**
     * Sets the value of the fld120 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld120(String value) {
        this.fld120 = value;
    }

    /**
     * Gets the value of the fld121 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld121() {
        return fld121;
    }

    /**
     * Sets the value of the fld121 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld121(String value) {
        this.fld121 = value;
    }

    /**
     * Gets the value of the fld122 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld122() {
        return fld122;
    }

    /**
     * Sets the value of the fld122 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld122(String value) {
        this.fld122 = value;
    }

    /**
     * Gets the value of the fld123 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld123() {
        return fld123;
    }

    /**
     * Sets the value of the fld123 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld123(String value) {
        this.fld123 = value;
    }

    /**
     * Gets the value of the fld124 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld124() {
        return fld124;
    }

    /**
     * Sets the value of the fld124 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld124(String value) {
        this.fld124 = value;
    }

    /**
     * Gets the value of the fld125 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld125() {
        return fld125;
    }

    /**
     * Sets the value of the fld125 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld125(String value) {
        this.fld125 = value;
    }

    /**
     * Gets the value of the fld126 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld126() {
        return fld126;
    }

    /**
     * Sets the value of the fld126 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld126(String value) {
        this.fld126 = value;
    }

    /**
     * Gets the value of the fld127 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld127() {
        return fld127;
    }

    /**
     * Sets the value of the fld127 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld127(String value) {
        this.fld127 = value;
    }

    /**
     * Gets the value of the fld128 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFld128() {
        return fld128;
    }

    /**
     * Sets the value of the fld128 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFld128(String value) {
        this.fld128 = value;
    }

    public String toString() {
        StringBuffer b = new StringBuffer();
        Method methods[] = Iso.class.getMethods();

        for (Method m : methods) {
            if (m.getName().startsWith("get")) {
                try {
                    b.append(m.getName().substring(3) + "='" + m.invoke(this) + "'\n");
                } catch (IllegalArgumentException e) {
                    e.printStackTrace();
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                } catch (InvocationTargetException e) {
                    e.printStackTrace();
                }
            }

        }
        return b.toString();
    }

}
