//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.29 at 03:28:07 PM EEST 
//


package lv.bank.cards.auth;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the lv.bank.cards.auth package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fld010_QNAME = new QName("", "fld010");
    private final static QName _Fld019_QNAME = new QName("", "fld019");
    private final static QName _Fld114_QNAME = new QName("", "fld114");
    private final static QName _Fld029_QNAME = new QName("", "fld029");
    private final static QName _Fld034_QNAME = new QName("", "fld034");
    private final static QName _Fld041_QNAME = new QName("", "fld041");
    private final static QName _Fld098_QNAME = new QName("", "fld098");
    private final static QName _Fld113_QNAME = new QName("", "fld113");
    private final static QName _Fld007_QNAME = new QName("", "fld007");
    private final static QName _Fld045_QNAME = new QName("", "fld045");
    private final static QName _Fld024_QNAME = new QName("", "fld024");
    private final static QName _Fld027_QNAME = new QName("", "fld027");
    private final static QName _Fld038_QNAME = new QName("", "fld038");
    private final static QName _Fld011_QNAME = new QName("", "fld011");
    private final static QName _Fld086_QNAME = new QName("", "fld086");
    private final static QName _Fld017_QNAME = new QName("", "fld017");
    private final static QName _Fld032_QNAME = new QName("", "fld032");
    private final static QName _Fld085_QNAME = new QName("", "fld085");
    private final static QName _Fld122_QNAME = new QName("", "fld122");
    private final static QName _Fld042_QNAME = new QName("", "fld042");
    private final static QName _Fld072_QNAME = new QName("", "fld072");
    private final static QName _Fld121_QNAME = new QName("", "fld121");
    private final static QName _Fld020_QNAME = new QName("", "fld020");
    private final static QName _Fld059_QNAME = new QName("", "fld059");
    private final static QName _Fld064_QNAME = new QName("", "fld064");
    private final static QName _Fld015_QNAME = new QName("", "fld015");
    private final static QName _Fld026_QNAME = new QName("", "fld026");
    private final static QName _Fld117_QNAME = new QName("", "fld117");
    private final static QName _Fld120_QNAME = new QName("", "fld120");
    private final static QName _Fld088_QNAME = new QName("", "fld088");
    private final static QName _Fld035_QNAME = new QName("", "fld035");
    private final static QName _Fld116_QNAME = new QName("", "fld116");
    private final static QName _Fld118_QNAME = new QName("", "fld118");
    private final static QName _Fld000_QNAME = new QName("", "fld000");
    private final static QName _Fld057_QNAME = new QName("", "fld057");
    private final static QName _Fld123_QNAME = new QName("", "fld123");
    private final static QName _Fld104_QNAME = new QName("", "fld104");
    private final static QName _Fld073_QNAME = new QName("", "fld073");
    private final static QName _Fld115_QNAME = new QName("", "fld115");
    private final static QName _Fld096_QNAME = new QName("", "fld096");
    private final static QName _Fld058_QNAME = new QName("", "fld058");
    private final static QName _Fld013_QNAME = new QName("", "fld013");
    private final static QName _Fld036_QNAME = new QName("", "fld036");
    private final static QName _Fld084_QNAME = new QName("", "fld084");
    private final static QName _Fld063_QNAME = new QName("", "fld063");
    private final static QName _Fld060_QNAME = new QName("", "fld060");
    private final static QName _Fld095_QNAME = new QName("", "fld095");
    private final static QName _Fld071_QNAME = new QName("", "fld071");
    private final static QName _Fld012_QNAME = new QName("", "fld012");
    private final static QName _Fld049_QNAME = new QName("", "fld049");
    private final static QName _Fld091_QNAME = new QName("", "fld091");
    private final static QName _Fld099_QNAME = new QName("", "fld099");
    private final static QName _Fld056_QNAME = new QName("", "fld056");
    private final static QName _Fld070_QNAME = new QName("", "fld070");
    private final static QName _Fld016_QNAME = new QName("", "fld016");
    private final static QName _Fld090_QNAME = new QName("", "fld090");
    private final static QName _Fld039_QNAME = new QName("", "fld039");
    private final static QName _Fld119_QNAME = new QName("", "fld119");
    private final static QName _Fld054_QNAME = new QName("", "fld054");
    private final static QName _Fld025_QNAME = new QName("", "fld025");
    private final static QName _Fld048_QNAME = new QName("", "fld048");
    private final static QName _Fld092_QNAME = new QName("", "fld092");
    private final static QName _Fld018_QNAME = new QName("", "fld018");
    private final static QName _Fld075_QNAME = new QName("", "fld075");
    private final static QName _Fld037_QNAME = new QName("", "fld037");
    private final static QName _Fld080_QNAME = new QName("", "fld080");
    private final static QName _Fld094_QNAME = new QName("", "fld094");
    private final static QName _Fld074_QNAME = new QName("", "fld074");
    private final static QName _Fld097_QNAME = new QName("", "fld097");
    private final static QName _Fld082_QNAME = new QName("", "fld082");
    private final static QName _Fld028_QNAME = new QName("", "fld028");
    private final static QName _Fld081_QNAME = new QName("", "fld081");
    private final static QName _Fld127_QNAME = new QName("", "fld127");
    private final static QName _Fld112_QNAME = new QName("", "fld112");
    private final static QName _Fld004_QNAME = new QName("", "fld004");
    private final static QName _Fld078_QNAME = new QName("", "fld078");
    private final static QName _Fld093_QNAME = new QName("", "fld093");
    private final static QName _Fld068_QNAME = new QName("", "fld068");
    private final static QName _Fld047_QNAME = new QName("", "fld047");
    private final static QName _Fld076_QNAME = new QName("", "fld076");
    private final static QName _Fld044_QNAME = new QName("", "fld044");
    private final static QName _Fld124_QNAME = new QName("", "fld124");
    private final static QName _Fld055_QNAME = new QName("", "fld055");
    private final static QName _Fld001_QNAME = new QName("", "fld001");
    private final static QName _Fld083_QNAME = new QName("", "fld083");
    private final static QName _Fld101_QNAME = new QName("", "fld101");
    private final static QName _Fld126_QNAME = new QName("", "fld126");
    private final static QName _Fld003_QNAME = new QName("", "fld003");
    private final static QName _Fld111_QNAME = new QName("", "fld111");
    private final static QName _Fld100_QNAME = new QName("", "fld100");
    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _Fld079_QNAME = new QName("", "fld079");
    private final static QName _Fld043_QNAME = new QName("", "fld043");
    private final static QName _Fld006_QNAME = new QName("", "fld006");
    private final static QName _Fld125_QNAME = new QName("", "fld125");
    private final static QName _Fld103_QNAME = new QName("", "fld103");
    private final static QName _Fld065_QNAME = new QName("", "fld065");
    private final static QName _Fld002_QNAME = new QName("", "fld002");
    private final static QName _Fld128_QNAME = new QName("", "fld128");
    private final static QName _Fld014_QNAME = new QName("", "fld014");
    private final static QName _Fld109_QNAME = new QName("", "fld109");
    private final static QName _Fld061_QNAME = new QName("", "fld061");
    private final static QName _Fld005_QNAME = new QName("", "fld005");
    private final static QName _Fld107_QNAME = new QName("", "fld107");
    private final static QName _Fld106_QNAME = new QName("", "fld106");
    private final static QName _Fld023_QNAME = new QName("", "fld023");
    private final static QName _Fld067_QNAME = new QName("", "fld067");
    private final static QName _Fld105_QNAME = new QName("", "fld105");
    private final static QName _Fld040_QNAME = new QName("", "fld040");
    private final static QName _Fld046_QNAME = new QName("", "fld046");
    private final static QName _Fld108_QNAME = new QName("", "fld108");
    private final static QName _Fld062_QNAME = new QName("", "fld062");
    private final static QName _Fld021_QNAME = new QName("", "fld021");
    private final static QName _Fld050_QNAME = new QName("", "fld050");
    private final static QName _Fld009_QNAME = new QName("", "fld009");
    private final static QName _Fld069_QNAME = new QName("", "fld069");
    private final static QName _Fld053_QNAME = new QName("", "fld053");
    private final static QName _Fld022_QNAME = new QName("", "fld022");
    private final static QName _Fld033_QNAME = new QName("", "fld033");
    private final static QName _Fld110_QNAME = new QName("", "fld110");
    private final static QName _Fld031_QNAME = new QName("", "fld031");
    private final static QName _Fld077_QNAME = new QName("", "fld077");
    private final static QName _Fld066_QNAME = new QName("", "fld066");
    private final static QName _Fld087_QNAME = new QName("", "fld087");
    private final static QName _Fld052_QNAME = new QName("", "fld052");
    private final static QName _Fld102_QNAME = new QName("", "fld102");
    private final static QName _Fld030_QNAME = new QName("", "fld030");
    private final static QName _Fld089_QNAME = new QName("", "fld089");
    private final static QName _Fld051_QNAME = new QName("", "fld051");
    private final static QName _Fld008_QNAME = new QName("", "fld008");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lv.bank.cards.auth
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Iso }
     */
    public Iso createIso() {
        return new Iso();
    }

    /**
     * Create an instance of {@link AuthRequest }
     */
    public AuthRequest createAuthRequest() {
        return new AuthRequest();
    }

    /**
     * Create an instance of {@link AuthResponse }
     */
    public AuthResponse createAuthResponse() {
        return new AuthResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld010")
    public JAXBElement<String> createFld010(String value) {
        return new JAXBElement<String>(_Fld010_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld019")
    public JAXBElement<String> createFld019(String value) {
        return new JAXBElement<String>(_Fld019_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld114")
    public JAXBElement<String> createFld114(String value) {
        return new JAXBElement<String>(_Fld114_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld029")
    public JAXBElement<String> createFld029(String value) {
        return new JAXBElement<String>(_Fld029_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld034")
    public JAXBElement<String> createFld034(String value) {
        return new JAXBElement<String>(_Fld034_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld041")
    public JAXBElement<String> createFld041(String value) {
        return new JAXBElement<String>(_Fld041_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld098")
    public JAXBElement<String> createFld098(String value) {
        return new JAXBElement<String>(_Fld098_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld113")
    public JAXBElement<String> createFld113(String value) {
        return new JAXBElement<String>(_Fld113_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld007")
    public JAXBElement<String> createFld007(String value) {
        return new JAXBElement<String>(_Fld007_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld045")
    public JAXBElement<String> createFld045(String value) {
        return new JAXBElement<String>(_Fld045_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld024")
    public JAXBElement<String> createFld024(String value) {
        return new JAXBElement<String>(_Fld024_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld027")
    public JAXBElement<String> createFld027(String value) {
        return new JAXBElement<String>(_Fld027_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld038")
    public JAXBElement<String> createFld038(String value) {
        return new JAXBElement<String>(_Fld038_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld011")
    public JAXBElement<String> createFld011(String value) {
        return new JAXBElement<String>(_Fld011_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld086")
    public JAXBElement<String> createFld086(String value) {
        return new JAXBElement<String>(_Fld086_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld017")
    public JAXBElement<String> createFld017(String value) {
        return new JAXBElement<String>(_Fld017_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld032")
    public JAXBElement<String> createFld032(String value) {
        return new JAXBElement<String>(_Fld032_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld085")
    public JAXBElement<String> createFld085(String value) {
        return new JAXBElement<String>(_Fld085_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld122")
    public JAXBElement<String> createFld122(String value) {
        return new JAXBElement<String>(_Fld122_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld042")
    public JAXBElement<String> createFld042(String value) {
        return new JAXBElement<String>(_Fld042_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld072")
    public JAXBElement<String> createFld072(String value) {
        return new JAXBElement<String>(_Fld072_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld121")
    public JAXBElement<String> createFld121(String value) {
        return new JAXBElement<String>(_Fld121_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld020")
    public JAXBElement<String> createFld020(String value) {
        return new JAXBElement<String>(_Fld020_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld059")
    public JAXBElement<String> createFld059(String value) {
        return new JAXBElement<String>(_Fld059_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld064")
    public JAXBElement<String> createFld064(String value) {
        return new JAXBElement<String>(_Fld064_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld015")
    public JAXBElement<String> createFld015(String value) {
        return new JAXBElement<String>(_Fld015_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld026")
    public JAXBElement<String> createFld026(String value) {
        return new JAXBElement<String>(_Fld026_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld117")
    public JAXBElement<String> createFld117(String value) {
        return new JAXBElement<String>(_Fld117_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld120")
    public JAXBElement<String> createFld120(String value) {
        return new JAXBElement<String>(_Fld120_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld088")
    public JAXBElement<String> createFld088(String value) {
        return new JAXBElement<String>(_Fld088_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld035")
    public JAXBElement<String> createFld035(String value) {
        return new JAXBElement<String>(_Fld035_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld116")
    public JAXBElement<String> createFld116(String value) {
        return new JAXBElement<String>(_Fld116_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld118")
    public JAXBElement<String> createFld118(String value) {
        return new JAXBElement<String>(_Fld118_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld000")
    public JAXBElement<String> createFld000(String value) {
        return new JAXBElement<String>(_Fld000_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld057")
    public JAXBElement<String> createFld057(String value) {
        return new JAXBElement<String>(_Fld057_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld123")
    public JAXBElement<String> createFld123(String value) {
        return new JAXBElement<String>(_Fld123_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld104")
    public JAXBElement<String> createFld104(String value) {
        return new JAXBElement<String>(_Fld104_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld073")
    public JAXBElement<String> createFld073(String value) {
        return new JAXBElement<String>(_Fld073_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld115")
    public JAXBElement<String> createFld115(String value) {
        return new JAXBElement<String>(_Fld115_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld096")
    public JAXBElement<String> createFld096(String value) {
        return new JAXBElement<String>(_Fld096_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld058")
    public JAXBElement<String> createFld058(String value) {
        return new JAXBElement<String>(_Fld058_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld013")
    public JAXBElement<String> createFld013(String value) {
        return new JAXBElement<String>(_Fld013_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld036")
    public JAXBElement<String> createFld036(String value) {
        return new JAXBElement<String>(_Fld036_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld084")
    public JAXBElement<String> createFld084(String value) {
        return new JAXBElement<String>(_Fld084_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld063")
    public JAXBElement<String> createFld063(String value) {
        return new JAXBElement<String>(_Fld063_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld060")
    public JAXBElement<String> createFld060(String value) {
        return new JAXBElement<String>(_Fld060_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld095")
    public JAXBElement<String> createFld095(String value) {
        return new JAXBElement<String>(_Fld095_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld071")
    public JAXBElement<String> createFld071(String value) {
        return new JAXBElement<String>(_Fld071_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld012")
    public JAXBElement<String> createFld012(String value) {
        return new JAXBElement<String>(_Fld012_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld049")
    public JAXBElement<String> createFld049(String value) {
        return new JAXBElement<String>(_Fld049_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld091")
    public JAXBElement<String> createFld091(String value) {
        return new JAXBElement<String>(_Fld091_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld099")
    public JAXBElement<String> createFld099(String value) {
        return new JAXBElement<String>(_Fld099_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld056")
    public JAXBElement<String> createFld056(String value) {
        return new JAXBElement<String>(_Fld056_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld070")
    public JAXBElement<String> createFld070(String value) {
        return new JAXBElement<String>(_Fld070_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld016")
    public JAXBElement<String> createFld016(String value) {
        return new JAXBElement<String>(_Fld016_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld090")
    public JAXBElement<String> createFld090(String value) {
        return new JAXBElement<String>(_Fld090_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld039")
    public JAXBElement<String> createFld039(String value) {
        return new JAXBElement<String>(_Fld039_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld119")
    public JAXBElement<String> createFld119(String value) {
        return new JAXBElement<String>(_Fld119_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld054")
    public JAXBElement<String> createFld054(String value) {
        return new JAXBElement<String>(_Fld054_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld025")
    public JAXBElement<String> createFld025(String value) {
        return new JAXBElement<String>(_Fld025_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld048")
    public JAXBElement<String> createFld048(String value) {
        return new JAXBElement<String>(_Fld048_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld092")
    public JAXBElement<String> createFld092(String value) {
        return new JAXBElement<String>(_Fld092_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld018")
    public JAXBElement<String> createFld018(String value) {
        return new JAXBElement<String>(_Fld018_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld075")
    public JAXBElement<String> createFld075(String value) {
        return new JAXBElement<String>(_Fld075_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld037")
    public JAXBElement<String> createFld037(String value) {
        return new JAXBElement<String>(_Fld037_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld080")
    public JAXBElement<String> createFld080(String value) {
        return new JAXBElement<String>(_Fld080_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld094")
    public JAXBElement<String> createFld094(String value) {
        return new JAXBElement<String>(_Fld094_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld074")
    public JAXBElement<String> createFld074(String value) {
        return new JAXBElement<String>(_Fld074_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld097")
    public JAXBElement<String> createFld097(String value) {
        return new JAXBElement<String>(_Fld097_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld082")
    public JAXBElement<String> createFld082(String value) {
        return new JAXBElement<String>(_Fld082_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld028")
    public JAXBElement<String> createFld028(String value) {
        return new JAXBElement<String>(_Fld028_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld081")
    public JAXBElement<String> createFld081(String value) {
        return new JAXBElement<String>(_Fld081_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld127")
    public JAXBElement<String> createFld127(String value) {
        return new JAXBElement<String>(_Fld127_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld112")
    public JAXBElement<String> createFld112(String value) {
        return new JAXBElement<String>(_Fld112_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld004")
    public JAXBElement<String> createFld004(String value) {
        return new JAXBElement<String>(_Fld004_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld078")
    public JAXBElement<String> createFld078(String value) {
        return new JAXBElement<String>(_Fld078_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld093")
    public JAXBElement<String> createFld093(String value) {
        return new JAXBElement<String>(_Fld093_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld068")
    public JAXBElement<String> createFld068(String value) {
        return new JAXBElement<String>(_Fld068_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld047")
    public JAXBElement<String> createFld047(String value) {
        return new JAXBElement<String>(_Fld047_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld076")
    public JAXBElement<String> createFld076(String value) {
        return new JAXBElement<String>(_Fld076_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld044")
    public JAXBElement<String> createFld044(String value) {
        return new JAXBElement<String>(_Fld044_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld124")
    public JAXBElement<String> createFld124(String value) {
        return new JAXBElement<String>(_Fld124_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld055")
    public JAXBElement<String> createFld055(String value) {
        return new JAXBElement<String>(_Fld055_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld001")
    public JAXBElement<String> createFld001(String value) {
        return new JAXBElement<String>(_Fld001_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld083")
    public JAXBElement<String> createFld083(String value) {
        return new JAXBElement<String>(_Fld083_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld101")
    public JAXBElement<String> createFld101(String value) {
        return new JAXBElement<String>(_Fld101_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld126")
    public JAXBElement<String> createFld126(String value) {
        return new JAXBElement<String>(_Fld126_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld003")
    public JAXBElement<String> createFld003(String value) {
        return new JAXBElement<String>(_Fld003_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld111")
    public JAXBElement<String> createFld111(String value) {
        return new JAXBElement<String>(_Fld111_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld100")
    public JAXBElement<String> createFld100(String value) {
        return new JAXBElement<String>(_Fld100_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld079")
    public JAXBElement<String> createFld079(String value) {
        return new JAXBElement<String>(_Fld079_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld043")
    public JAXBElement<String> createFld043(String value) {
        return new JAXBElement<String>(_Fld043_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld006")
    public JAXBElement<String> createFld006(String value) {
        return new JAXBElement<String>(_Fld006_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld125")
    public JAXBElement<String> createFld125(String value) {
        return new JAXBElement<String>(_Fld125_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld103")
    public JAXBElement<String> createFld103(String value) {
        return new JAXBElement<String>(_Fld103_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld065")
    public JAXBElement<String> createFld065(String value) {
        return new JAXBElement<String>(_Fld065_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld002")
    public JAXBElement<String> createFld002(String value) {
        return new JAXBElement<String>(_Fld002_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld128")
    public JAXBElement<String> createFld128(String value) {
        return new JAXBElement<String>(_Fld128_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld014")
    public JAXBElement<String> createFld014(String value) {
        return new JAXBElement<String>(_Fld014_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld109")
    public JAXBElement<String> createFld109(String value) {
        return new JAXBElement<String>(_Fld109_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld061")
    public JAXBElement<String> createFld061(String value) {
        return new JAXBElement<String>(_Fld061_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld005")
    public JAXBElement<String> createFld005(String value) {
        return new JAXBElement<String>(_Fld005_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld107")
    public JAXBElement<String> createFld107(String value) {
        return new JAXBElement<String>(_Fld107_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld106")
    public JAXBElement<String> createFld106(String value) {
        return new JAXBElement<String>(_Fld106_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld023")
    public JAXBElement<String> createFld023(String value) {
        return new JAXBElement<String>(_Fld023_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld067")
    public JAXBElement<String> createFld067(String value) {
        return new JAXBElement<String>(_Fld067_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld105")
    public JAXBElement<String> createFld105(String value) {
        return new JAXBElement<String>(_Fld105_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld040")
    public JAXBElement<String> createFld040(String value) {
        return new JAXBElement<String>(_Fld040_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld046")
    public JAXBElement<String> createFld046(String value) {
        return new JAXBElement<String>(_Fld046_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld108")
    public JAXBElement<String> createFld108(String value) {
        return new JAXBElement<String>(_Fld108_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld062")
    public JAXBElement<String> createFld062(String value) {
        return new JAXBElement<String>(_Fld062_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld021")
    public JAXBElement<String> createFld021(String value) {
        return new JAXBElement<String>(_Fld021_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld050")
    public JAXBElement<String> createFld050(String value) {
        return new JAXBElement<String>(_Fld050_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld009")
    public JAXBElement<String> createFld009(String value) {
        return new JAXBElement<String>(_Fld009_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld069")
    public JAXBElement<String> createFld069(String value) {
        return new JAXBElement<String>(_Fld069_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld053")
    public JAXBElement<String> createFld053(String value) {
        return new JAXBElement<String>(_Fld053_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld022")
    public JAXBElement<String> createFld022(String value) {
        return new JAXBElement<String>(_Fld022_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld033")
    public JAXBElement<String> createFld033(String value) {
        return new JAXBElement<String>(_Fld033_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld110")
    public JAXBElement<String> createFld110(String value) {
        return new JAXBElement<String>(_Fld110_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld031")
    public JAXBElement<String> createFld031(String value) {
        return new JAXBElement<String>(_Fld031_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld077")
    public JAXBElement<String> createFld077(String value) {
        return new JAXBElement<String>(_Fld077_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld066")
    public JAXBElement<String> createFld066(String value) {
        return new JAXBElement<String>(_Fld066_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld087")
    public JAXBElement<String> createFld087(String value) {
        return new JAXBElement<String>(_Fld087_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld052")
    public JAXBElement<String> createFld052(String value) {
        return new JAXBElement<String>(_Fld052_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld102")
    public JAXBElement<String> createFld102(String value) {
        return new JAXBElement<String>(_Fld102_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld030")
    public JAXBElement<String> createFld030(String value) {
        return new JAXBElement<String>(_Fld030_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld089")
    public JAXBElement<String> createFld089(String value) {
        return new JAXBElement<String>(_Fld089_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld051")
    public JAXBElement<String> createFld051(String value) {
        return new JAXBElement<String>(_Fld051_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fld008")
    public JAXBElement<String> createFld008(String value) {
        return new JAXBElement<String>(_Fld008_QNAME, String.class, null, value);
    }

}
