package lv.bank.cards.soap.api.atm.soap.servise;

import lv.bank.cards.soap.api.atm.soap.types.Block;
import lv.bank.cards.soap.api.atm.soap.types.BlockResponse;
import lv.bank.cards.soap.api.atm.soap.types.Get;
import lv.bank.cards.soap.api.atm.soap.types.GetClientID;
import lv.bank.cards.soap.api.atm.soap.types.GetClientIDResponse;
import lv.bank.cards.soap.api.atm.soap.types.GetList;
import lv.bank.cards.soap.api.atm.soap.types.GetListResponse;
import lv.bank.cards.soap.api.atm.soap.types.GetResponse;
import lv.bank.cards.soap.api.atm.soap.types.ObjectFactory;
import lv.bank.cards.soap.api.atm.soap.types.PaymentServerFault;
import lv.bank.cards.soap.api.atm.soap.types.Return;
import lv.bank.cards.soap.api.atm.soap.types.ReturnResponse;
import lv.bank.cards.soap.api.atm.soap.types.Unblock;
import lv.bank.cards.soap.api.atm.soap.types.UnblockResponse;
import lv.bank.cards.soap.api.atm.soap.types.WriteOff;
import lv.bank.cards.soap.api.atm.soap.types.WriteOffResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-11-04T13:59:23.651+02:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "urn:PaymentServer", name = "ServiceProviderPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceProviderPort {

    @WebMethod(operationName = "Block", action = "urn:PaymentServer")
    @WebResult(name = "BlockResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public BlockResponse block(

        @WebParam(partName = "body", name = "Block", targetNamespace = "urn:PaymentServer")
                Block body
    ) throws PaymentServerFault;

    @WebMethod(operationName = "Unblock", action = "urn:PaymentServer")
    @WebResult(name = "UnblockResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public UnblockResponse unblock(

        @WebParam(partName = "body", name = "Unblock", targetNamespace = "urn:PaymentServer")
                Unblock body
    ) throws PaymentServerFault;

    @WebMethod(operationName = "WriteOff", action = "urn:PaymentServer")
    @WebResult(name = "WriteOffResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public WriteOffResponse writeOff(

        @WebParam(partName = "body", name = "WriteOff", targetNamespace = "urn:PaymentServer")
                WriteOff body
    ) throws PaymentServerFault;

    @WebMethod(operationName = "GetList", action = "urn:PaymentServer")
    @WebResult(name = "GetListResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public GetListResponse getList(

        @WebParam(partName = "body", name = "GetList", targetNamespace = "urn:PaymentServer")
                GetList body
    ) throws PaymentServerFault;

    @WebMethod(operationName = "Return", action = "urn:PaymentServer")
    @WebResult(name = "ReturnResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public ReturnResponse _return(

        @WebParam(partName = "body", name = "Return", targetNamespace = "urn:PaymentServer")
                Return body
    ) throws PaymentServerFault;

    @WebMethod(operationName = "GetClientID", action = "urn:PaymentServer")
    @WebResult(name = "GetClientIDResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public GetClientIDResponse getClientID(

        @WebParam(partName = "body", name = "GetClientID", targetNamespace = "urn:PaymentServer")
                GetClientID body
    ) throws PaymentServerFault;

    @WebMethod(operationName = "Get", action = "urn:PaymentServer")
    @WebResult(name = "GetResponse", targetNamespace = "urn:PaymentServer", partName = "body")
    public GetResponse get(

        @WebParam(partName = "body", name = "Get", targetNamespace = "urn:PaymentServer")
                Get body
    ) throws PaymentServerFault;
}
