/*
 * Generated by XDoclet - Do not edit!
 */
package lv.nordlb.cards.transmaster.bo.interfaces;

import lv.bank.cards.core.entity.cms.IzdCompany;
import lv.bank.cards.core.entity.cms.IzdConfig;
import lv.bank.cards.core.entity.cms.IzdCountry;
import lv.bank.cards.core.entity.cms.IzdStopCause;
import lv.bank.cards.core.utils.DataIntegrityException;
import org.hibernate.SQLQuery;

import javax.ejb.Local;
import java.util.List;

@Local
public interface CommonManager {

    String COMP_NAME = "java:comp/env/ejb/CommonManager";
    String JNDI_NAME = "java:app/bankCards/CommonManagerBean";

    Integer getFileId(String bankc, String groupc, String fileType, String jjj);

    String getBranchIdByExternalId(String externalId);

    IzdCompany getIzdCompanyByRegCodeUR(String regCodeUR) throws DataIntegrityException;

    IzdCompany getIzdCompanyByCode(String code, String bankc) throws DataIntegrityException;

    IzdStopCause getIzdStopCauseByCause(String cause) throws DataIntegrityException;

    IzdCountry getIzdCountryByShortCountryCode(String code) throws DataIntegrityException;

    List<IzdConfig> GetIzdConfig();

    SQLQuery getDeliveryBranchDataHandoff(String bankCode, String groupCode);
}
